# Generated by Django 3.2.2 on 2021-05-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_beverages_desserts_veg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'gallery1',
            },
        ),
        migrations.CreateModel(
            name='Gallery2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallerytype', to='store.gallery1')),
            ],
            options={
                'verbose_name_plural': 'gallery2',
            },
        ),
    ]
