# Generated by Django 3.2.2 on 2021-05-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_category_gallery1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery2',
            name='name',
            field=models.CharField(db_index=True, default='abc', max_length=255),
        ),
    ]
