# Generated by Django 3.2.2 on 2021-05-13 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='allItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='images/')),
                ('time', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'allitems',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('streetaddress', models.CharField(default='abc', max_length=255)),
                ('locality', models.CharField(default='abc', max_length=255)),
                ('city', models.CharField(default='abc', max_length=255)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('streetaddress', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.allitems')),
            ],
        ),
    ]
