# Generated by Django 3.2.2 on 2021-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_allitems_check_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='allitems',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
    ]
