# Generated by Django 3.2.2 on 2021-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_allitems_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cardno', models.IntegerField()),
                ('cardname', models.CharField(max_length=255)),
                ('cvv', models.IntegerField()),
                ('expmonth', models.IntegerField()),
                ('expyr', models.IntegerField()),
            ],
        ),
    ]
