# Generated by Django 3.2.2 on 2021-05-17 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(default='0')),
                ('stars', models.DecimalField(decimal_places=1, default='0.0', max_digits=1)),
                ('adult', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('streetaddress', models.CharField(default='abc', max_length=255)),
                ('locality', models.CharField(default='abc', max_length=255)),
                ('city', models.CharField(default='abc', max_length=255)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('checkin', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('stars', models.DecimalField(decimal_places=1, default='0.0', max_digits=1)),
                ('streetaddress', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.room')),
            ],
        ),
    ]
