# Generated by Django 3.2.2 on 2021-05-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_room_roomcheck_roomorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomorder',
            name='stars',
        ),
    ]
