# Generated by Django 3.2.2 on 2021-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_roomorder_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='stars',
            field=models.IntegerField(default='0'),
        ),
    ]
