# Generated by Django 3.2.2 on 2021-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_room_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
