# Generated by Django 3.2.2 on 2021-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverages',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='desserts',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nonveg',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliverystatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='resprepstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veg',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
