# Generated by Django 3.2.2 on 2021-05-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='resprepstatus',
            field=models.BooleanField(default=True),
        ),
    ]
